app:
    site_name: Text Recognition
    host: 0.0.0.0
    port: 7000

postgres:
  user: postgres
  password: postgres
  database: tesseract
  port: 5432
  host: localhost

redis:
  port: 6379
  host: localhost