app:
    host: 0.0.0.0
    port: 5000
    workers: 1

postgres:
    user: postgres
    password: postgres
    database: tesseract
    port: 5432
    host: db

redis:
    port: 6379
    host: redis

jwt_auth:
    jwt_secret: JdfbbS34pPsdnjFZd31D
    jwt_algorithm: HS256
    jset_exp_delta_seconds: 7200